server:
  port: 8081
  #TODO cors disable

api-otp:
  #host: api-otp  
  host: localhost
  port: 8082

ep-manager:
  #host: ep-manager  
  host: localhost
  port: 8083

db:
  #uri: mongodb://db/
  uri: mongodb://localhost:8085/
  name: ojp
  collection: api_ojp

services:
  OJPExchangePointsRequest: true
  OJPLocationInformationRequest: true
  OJPStopEventRequest: true
  OJPTripRequest: true
  #OJPMultiPointTripRequest: true
  #OJPTripInfoRequest: true
