environments:
  default: prod
  #default environment if NODE_ENV is not defined
prod:
  server:
    port: 9091
    logrequest: ${LOG_REQUEST}
  api-otp:
    host: api-otp
    port: 9092
  ep-manager:
    host: ep-manager
    port: 9093
  db:
    uri: mongodb://db/
    name: ojp
    collection: api_ojp
  logs:
    level: 'info'
    colorize: true
    ignore: 'pid,hostname'
dev:
  server:
    port: 8081
    logrequest: true
  api-otp:
    host: localhost
    port: 8082
  ep-manager:
    host: localhost
    port: 8083
  db:
    uri: mongodb://localhost:8085/
    name: ${prod.db.name}
    collection: ${prod.db.collection}
  logs:
    level: 'debug'
    colorize: false

default_restrictions:
  transfer_limit: 2
  include_accessibility: false
  include_intermediate_stops: false
  limit: 10000
  skip: 0

#enable disable services
services:
  OJPExchangePointsRequest: true
  OJPLocationInformationRequest: true
  OJPStopEventRequest: true
  OJPTripRequest: true
  OJPTripInfoRequest: true
  OJPMultiPointTripRequest: true

errors:
  notagrequest: NO_TAG_REQUEST_FOUND
  notagcondition: NO_CONDITIONS_REQUEST_FOUND
  noparsing: NO_PARSING_XML_REQUEST
  noresults:
    exchangepoints: EXCHANGEPOINTS_NO_RESULTS
    locations: LOCATION_NO_RESULTS
    stopevents: STOPEVENT_LOCATION_UNSERVED
    tripinfo: TRIPINFO_TRIP_UNAVAILABLE
    trip: TRIP_NO_TRIP_FOUND
