server:
  port: 8080
  #TODO cache_ttl: 0

db:
  uri: mongodb://db/
  #uri: mongodb://0.0.0.0:8085/
  name: ojp
  collection: exchange_points

services:
  OJPLocationInformation:
    enabled: true
  
  OJPStopEvent:
    enabled: true

  OJPExchangePoints:
    enabled: true
  
  OJPTrip:
    enabled: true

  OJPTripInfo:
    enabled: true

  OJPMultiPointTrip:
    enabled: true
