version: '3'

networks:
  default:
    driver: bridge

services:
  #TODO shared mongodb instance
  #mongodb:
  #  image:
  
  #TODO local testing instance of OpenTripPlanner
  # otp-test:
  #   container_name: otp-test
  #   image: openmove/otp:latest
  #   ports:
  #     - "8080:8080"    

  api-ojp:
    container_name: api-ojp
    image: openmove/api-ojp:latest
    build:
      context: ./modules/api-otp
    ports:
      - "8081:8081"      
    #environment:
    # depends_on:
    #   - ep-manager
    #   - otp

  api-otp:
    container_name: api-otp
    image: openmove/api-otp:latest
    build:
      context: ./modules/api-otp
    ports: 
      - "8082:8080"      

  ep-manager:
    container_name: ep-manager
    image: openmove/ep-manager:latest
    build:
      context: ./modules/ep-manager
    ports:
      - "8083:8083"

  xsd2json:
    container_name: xsd2json
    image: openmove/xsd2json:latest
    build:
      context: ./modules/xsd2json
    ports:
      - "8084:8084"      

  db:
    container_name: mongo
    image: mongo:latest
    ports:
      - "8085:27017"
    volumes:
      - ./modules/db/data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ojp   
