version: '3'

networks:
  default:
    driver: bridge

services:

  api-ojp:
    container_name: api-ojp
    image: ojp/api-ojp:latest
    build:
      context: ./modules/api-ojp
    ports:
      - "8081:9091"
    environment:
      - LOG_REQUEST=true
      - OTP_MAX_PARALLEL_REQUESTS=10
    depends_on:
      - db
      - api-otp
      - ep-manager

  api-otp:
    container_name: api-otp
    image: ojp/api-otp:latest
    build:
      context: ./modules/api-otp
    ports:
      - "9092:9092"
    environment:
      - OTP_HOST=mip-r-loadb-14949k90kol75-1272452334.eu-south-1.elb.amazonaws.com
      - OTP_PATH=/otp/routers/default/index/graphql
      - OTP_PORT=8080
      #- QUERY_DEBUG=true

  ep-manager:
    container_name: ep-manager
    image: ojp/ep-manager:latest
    build:
      context: ./modules/ep-manager
    ports:
      - "9093:9093"
    environment:
      - CSV_AUTOIMPORT=false
      - CSV_VERSION=0.16
      #- CSV_URL=https://remote.resource.com/exchangepoints.csv
    # volumes:
    #   - ./csvs:/home/csvs
    depends_on:
      - db

  db:
    container_name: db
    image: mongo:latest
    ports:
      - "9095:27017"
      - "8085:27017"
      #used also by dev environment
    volumes:
      - ./modules/db/data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ojp

  tests:
    container_name: tests
    image: ojp/tests:latest
    build:
      context: ./modules/tests
    ports:
      - "9096:9096"
    environment:
      - API_HOST=localhost
      - NODE_ENV=devdocker
      #only for local docke-compose
    depends_on:
      - api-ojp

  #TODO maybe un useful, used as library
  #  xsd2json:
  #   container_name: xsd2json
  #   image: ojp/xsd2json:latest
  #   build:
  #     context: ./modules/xsd2json
  #   ports:
  #     - "9094:9094"
