version: '3'

networks:
  default:
    driver: bridge

services:

  api-ojp:
    container_name: api-ojp
    image: ojp/api-ojp:latest
    build:
      context: ./modules/api-otp
    ports:
      - "8081:8081"      
    #environment:
    depends_on:
      - ep-manager
      - api-otp
      - db

  api-otp:
    container_name: api-otp
    image: ojp/api-otp:latest
    build:
      context: ./modules/api-otp
    ports: 
      - "8082:8082"      

  ep-manager:
    container_name: ep-manager
    image: ojp/ep-manager:latest
    build:
      context: ./modules/ep-manager
    ports:
      - "8083:8083"
    environment:
      - IMPORT=true
      - CSV_VERSION=0.16
    # volumes:
    #   - ./csvs:/home/csvs      
    depends_on:
      - db

  db:
    container_name: mongo
    image: mongo:latest
    ports:
      - "8085:27017"
    volumes:
      - ./modules/db/data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ojp

  tests:
    container_name: tests
    image: ojp/tests:latest
    build:
      context: ./tests
    ports:
      - "8086:8086" 

  #TODO maybe un useful, used as library
  #  xsd2json:
  #   container_name: xsd2json
  #   image: ojp/xsd2json:latest
  #   build:
  #     context: ./modules/xsd2json
  #   ports:
  #     - "8084:8084"      
