environments:
  default: prod
  #default environment if NODE_ENV is not defined
dev:
  server:
    port: 8082
  # otp:
  #   hostname: localhost
  #   path: /otp/routers/default
  #   port: 80    
prod:
  server:
    port: 9092

otp:
  hostname: map.muoversinpiemonte.it
  path: /otp/routers/mip
  port: 443
  headers:
    User-Agent: ojp-middleware-client
rest:
  path: /index
graphql:
  path: /index/graphql
