server:
  port: 8080
  #TODO cache_ttl: 0

endpoints:
  default:
    hostname: otp.example.com
    path: /otp/routers/default
    port: 443
    headers:
      User-Agent: ojp-middleware-client

  mip-rest:
    path: 

  mip-graphql:
    path:
