server:
  port: 8082
  #TODO cache_ttl: 0

otp:
  hostname: map.muoversinpiemonte.it
  path: /otp/routers/mip
  port: 443
  headers:
    User-Agent: ojp-middleware-client

rest:
  path: /index

graphql:
  path: /index/graphql
