server:
  port: 8090
  #TODO cache_ttl: 0

endpoints:
  default:
    hostname: map.muoversinpiemonte.it
    path: /otp/routers/mip
    port: 443
    headers:
      User-Agent: ojp-middleware-client

  rest:
    path: /index

  graphql:
    path: /index/graphql


