environments:
  default: prod
  #default environment if NODE_ENV is not defined
prod:
  server:
    port: 9092
  logs:
    level: 'info'
    colorize: true
    ignore: 'pid,hostname'
dev:
  server:
    port: 8082
  # otp: #local instance of opentripplanner
  #   hostname: localhost
  #   path: /otp/routers/default
  #   port: 80    
  logs:
    level: 'debug'
    colorize: false

otp:
  hostname: map.muoversinpiemonte.it
  path: /otp/routers/mip
  port: 443
  headers:
    User-Agent: ojp-middleware-client
rest:
  path: /index
graphql:
  path: /index/graphql
