environments:
  default: prod
  #default environment if NODE_ENV is not defined
prod:
  server:
    port: 9092
  logs:
    level: 'info'
    colorize: true
    ignore: 'pid,hostname'
  #caching: true

dev:
  server:
    port: 8082
  # otp: #local instance of opentripplanner
  #   hostname: localhost
  #   path: /otp/routers/default
  #   port: 8080
  logs:
    level: 'debug'
    colorize: false

otp:
  # host: map.muoversinpiemonte.it
  # path: /otp/routers/mip/index/graphql
  # port: 443
  host: ${OTP_HOST}
  path: ${OTP_PATH}
  port: ${OTP_PORT}
  headers:
    User-Agent: ojp-middleware

default_limit: 10000
default_skip: 0

caching: false
#caching OTP graphql query results